### ISSUE TITLE
Add parameter to wait animation or transition ending

### ISSUE THREAD

**Issue by evilebottnawi** [terwanerik/ScrollTrigger#31]
If you quickly roll the roller up and down, then the jumps are obtained, it would be great to be able to switch after classes only after the animation (transition) has ended.

**Comment by terwanerik** [comment]
The problem is that the animation duration is set in your css class, so you'd have to specify some kind of timeout via the data-scroll attribute or js API. I might implement this myself, but i'm not really seeing great benefit from this.

If you make a PR with the code, there is a great chance it'll make it in the next version.

**Comment by terwanerik** [comment]
I've added this to [New features in v3.0](https://github.com/terwanerik/ScrollTrigger/issues/31)
