### ISSUE TITLE
data-scroll-showCallback not calling function

### ISSUE THREAD

**Issue by megalofauna** [terwanerik/ScrollTrigger#33]
https://codepen.io/megalofauna/pen/bWYRKP

When you have time, I wonder if you could look over the pen above and let me know why the `data-scroll-showCallback` attribute does not call the function. 

I'm sure there's a simple reason I'm missing. 

BTW, awesome bit of work, this! If I could star your repo twice, I would. Thanks!

**Comment by terwanerik** [comment]
Thanks! 

The issue is that the function `myFunction` is not in the `window` scope, so ScrollTrigger cannot find it. You can assign the function `myFunction` to the `window` scope (e.g. `window.myFunction = function(){}`), or give the `ScrollTrigger` a custom `callScope`. The custom `callScope` is not properly documented, but does exist.

I created a [fork of your pen](https://codepen.io/erikterwan/pen/JNOpJP) to demonstrate the `callScope` functionality.

Thanks for the headsup, will make sure documentation for this is made.

**Comment by megalofauna** [comment]
Thanks, @terwanerik! Will use callScope from here on out! Awesome.

**Comment by cyclomaticlone** [comment]
Hi, sorry to hijack this, I'm relatively new to javascript and am trying to figure out how to set `callScope`. 

I've created a pen to illustrate what I'm trying: 
https://codepen.io/circlecircle/pen/NgKWbK

I know it's something to do with the way I'm setting `callScope`, if I modify line 291 in ScrollTrigger.js to my namespace, it works. 

Thanks for this project, has been very handy!

**Comment by cyclomaticlone** [comment]
Nevermind, I figured it out after looking at the pen you posted in reply to @megalofauna.

https://codepen.io/circlecircle/pen/OgLJzK
